apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metric-server-stack
spec:
  interval: 5m
  chart:
    spec:
      version: 3.8.2
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server/metrics-server
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: false
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux