apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/prometheus
- ../../base/grafana
- ../../base/polaris
- ../../base/pull-secret-patcher
- ../../base/metric-server
#patchesStrategicMerge:
#- dev-deployment.yaml