apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polaris-stack
spec:
  interval: 5m
  chart:
    spec:
      version: 5.0.0
      chart: fairwinds-stable/polaris
      sourceRef:
        kind: HelmRepository
        name: polaris-repository
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: false
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux