apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
#- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
#- prometheus.yaml
- prometheus-ns.yaml
---
helmCharts:
- name: prometheus-operator
  repo: https://charts.helm.sh/stable/
  version: 9.3.2
  releaseName: stable/prometheus-operator
  namespace: prometheus

#helmChartInflationGenerator:
#- chartName: minecraft
#  chartRepoUrl: https://kubernetes-charts.storage.googleapis.com
#  chartVersion: v1.2.0
#  releaseName: test
#  releaseNamespace: testNamespace